<?php

$text['title-databases']['en-us'] = "Databases";
$text['title-databases']['en-gb'] = "Databases";
$text['title-databases']['ar-eg'] = "قواعد بيانات";
$text['title-databases']['de-at'] = "Datenbanken"; //copied from de-de
$text['title-databases']['de-ch'] = "Datenbanken"; //copied from de-de
$text['title-databases']['de-de'] = "Datenbanken";
$text['title-databases']['es-cl'] = "Bases de datos";
$text['title-databases']['es-mx'] = "Bases de datos"; //copied from es-cl
$text['title-databases']['fr-ca'] = "Bases de données"; //copied from fr-fr
$text['title-databases']['fr-fr'] = "Bases de données";
$text['title-databases']['he-il'] = "מאגרי מידע";
$text['title-databases']['it-it'] = "Database";
$text['title-databases']['nl-nl'] = "Databases";
$text['title-databases']['pl-pl'] = "Bazy danych";
$text['title-databases']['pt-br'] = "Base de dados";
$text['title-databases']['pt-pt'] = "Bases de Dados";
$text['title-databases']['ro-ro'] = "Baze de date";
$text['title-databases']['ru-ru'] = "Базы даных";
$text['title-databases']['sv-se'] = "Databaser";
$text['title-databases']['uk-ua'] = "Бази даних";
$text['title-databases']['zh-cn'] = "数据库";
$text['title-databases']['ja-jp'] = "データベース";
$text['title-databases']['ko-kr'] = "데이터베이스";

$text['title-sql_query']['en-us'] = "SQL Query";
$text['title-sql_query']['en-gb'] = "SQL Query";
$text['title-sql_query']['ar-eg'] = "استعلام SQL";
$text['title-sql_query']['de-at'] = "Befehl"; //copied from de-de
$text['title-sql_query']['de-ch'] = "Befehl"; //copied from de-de
$text['title-sql_query']['de-de'] = "Befehl";
$text['title-sql_query']['es-cl'] = "Comando";
$text['title-sql_query']['es-mx'] = "Comando"; //copied from es-cl
$text['title-sql_query']['fr-ca'] = "Commande"; //copied from fr-fr
$text['title-sql_query']['fr-fr'] = "Commande";
$text['title-sql_query']['he-il'] = "שאילתת SQL";
$text['title-sql_query']['it-it'] = "Comando";
$text['title-sql_query']['nl-nl'] = "Commando";
$text['title-sql_query']['pl-pl'] = "Polecenie";
$text['title-sql_query']['pt-br'] = "Comando"; //copied from pt-pt
$text['title-sql_query']['pt-pt'] = "Comando";
$text['title-sql_query']['ro-ro'] = "Interogare SQL";
$text['title-sql_query']['ru-ru'] = "Команды";
$text['title-sql_query']['sv-se'] = "Kommando";
$text['title-sql_query']['uk-ua'] = "Команди";
$text['title-sql_query']['zh-cn'] = "SQL查询";
$text['title-sql_query']['ja-jp'] = "SQLクエリ";
$text['title-sql_query']['ko-kr'] = "SQL 쿼리";

$text['option-result_type_view']['en-us'] = "View";
$text['option-result_type_view']['en-gb'] = "View";
$text['option-result_type_view']['ar-eg'] = "منظر";
$text['option-result_type_view']['de-at'] = "Ansicht"; //copied from de-de
$text['option-result_type_view']['de-ch'] = "Ansicht"; //copied from de-de
$text['option-result_type_view']['de-de'] = "Ansicht";
$text['option-result_type_view']['es-cl'] = "Ver";
$text['option-result_type_view']['es-mx'] = "Ver"; //copied from es-cl
$text['option-result_type_view']['fr-ca'] = "Voir"; //copied from fr-fr
$text['option-result_type_view']['fr-fr'] = "Voir";
$text['option-result_type_view']['he-il'] = "נוף";
$text['option-result_type_view']['it-it'] = "Mostra";
$text['option-result_type_view']['nl-nl'] = "Bekijk";
$text['option-result_type_view']['pl-pl'] = "Widok";
$text['option-result_type_view']['pt-br'] = "Visualizar";
$text['option-result_type_view']['pt-pt'] = "Ver";
$text['option-result_type_view']['ro-ro'] = "Vedere";
$text['option-result_type_view']['ru-ru'] = "Просмотр";
$text['option-result_type_view']['sv-se'] = "Granska";
$text['option-result_type_view']['uk-ua'] = "Перегляд";
$text['option-result_type_view']['zh-cn'] = "看法";
$text['option-result_type_view']['ja-jp'] = "ビュー";
$text['option-result_type_view']['ko-kr'] = "보다";

$text['option-result_type_insert']['en-us'] = "SQL";
$text['option-result_type_insert']['en-gb'] = "SQL";
$text['option-result_type_insert']['ar-eg'] = "SQL";
$text['option-result_type_insert']['de-at'] = "SQL"; //copied from de-de
$text['option-result_type_insert']['de-ch'] = "SQL"; //copied from de-de
$text['option-result_type_insert']['de-de'] = "SQL";
$text['option-result_type_insert']['es-cl'] = "SQL";
$text['option-result_type_insert']['es-mx'] = "SQL"; //copied from es-cl
$text['option-result_type_insert']['fr-ca'] = "SQL"; //copied from fr-fr
$text['option-result_type_insert']['fr-fr'] = "SQL";
$text['option-result_type_insert']['he-il'] = "SQL";
$text['option-result_type_insert']['it-it'] = "SQL";
$text['option-result_type_insert']['nl-nl'] = "SQL";
$text['option-result_type_insert']['pl-pl'] = "SQL";
$text['option-result_type_insert']['pt-br'] = "SQL"; //copied from pt-pt
$text['option-result_type_insert']['pt-pt'] = "SQL";
$text['option-result_type_insert']['ro-ro'] = "SQL";
$text['option-result_type_insert']['ru-ru'] = "SQL";
$text['option-result_type_insert']['sv-se'] = "SQL";
$text['option-result_type_insert']['uk-ua'] = "SQL";
$text['option-result_type_insert']['zh-cn'] = "SQL";
$text['option-result_type_insert']['ja-jp'] = "SQL";
$text['option-result_type_insert']['ko-kr'] = "SQL";

$text['option-result_type_csv']['en-us'] = "CSV";
$text['option-result_type_csv']['en-gb'] = "CSV";
$text['option-result_type_csv']['ar-eg'] = "CSV";
$text['option-result_type_csv']['de-at'] = "CSV"; //copied from de-de
$text['option-result_type_csv']['de-ch'] = "CSV"; //copied from de-de
$text['option-result_type_csv']['de-de'] = "CSV";
$text['option-result_type_csv']['es-cl'] = "CSV";
$text['option-result_type_csv']['es-mx'] = "CSV"; //copied from es-cl
$text['option-result_type_csv']['fr-ca'] = "CSV"; //copied from fr-fr
$text['option-result_type_csv']['fr-fr'] = "CSV";
$text['option-result_type_csv']['he-il'] = "CSV";
$text['option-result_type_csv']['it-it'] = "CSV";
$text['option-result_type_csv']['nl-nl'] = "CSV";
$text['option-result_type_csv']['pl-pl'] = "CSV";
$text['option-result_type_csv']['pt-br'] = "CSV"; //copied from pt-pt
$text['option-result_type_csv']['pt-pt'] = "CSV";
$text['option-result_type_csv']['ro-ro'] = "CSV";
$text['option-result_type_csv']['ru-ru'] = "CSV";
$text['option-result_type_csv']['sv-se'] = "CSV";
$text['option-result_type_csv']['uk-ua'] = "CSV";
$text['option-result_type_csv']['zh-cn'] = "CSV";
$text['option-result_type_csv']['ja-jp'] = "CSV";
$text['option-result_type_csv']['ko-kr'] = "CSV";

$text['label-table']['en-us'] = "Table";
$text['label-table']['en-gb'] = "Table";
$text['label-table']['ar-eg'] = "طاولة";
$text['label-table']['de-at'] = "Tabelle"; //copied from de-de
$text['label-table']['de-ch'] = "Tabelle"; //copied from de-de
$text['label-table']['de-de'] = "Tabelle";
$text['label-table']['es-cl'] = "Tabla";
$text['label-table']['es-mx'] = "Tabla"; //copied from es-cl
$text['label-table']['fr-ca'] = "Table"; //copied from fr-fr
$text['label-table']['fr-fr'] = "Table";
$text['label-table']['he-il'] = "שולחן";
$text['label-table']['it-it'] = "Tabella";
$text['label-table']['nl-nl'] = "Tabel";
$text['label-table']['pl-pl'] = "Tabela";
$text['label-table']['pt-br'] = "Tabela"; //copied from pt-pt
$text['label-table']['pt-pt'] = "Tabela";
$text['label-table']['ro-ro'] = "Masa";
$text['label-table']['ru-ru'] = "Таблица";
$text['label-table']['sv-se'] = "TAbell";
$text['label-table']['uk-ua'] = "Таблиця";
$text['label-table']['zh-cn'] = "桌子";
$text['label-table']['ja-jp'] = "テーブル";
$text['label-table']['ko-kr'] = "테이블";

$text['label-switch']['en-us'] = "Switch";
$text['label-switch']['en-gb'] = "Switch";
$text['label-switch']['ar-eg'] = "يُحوّل";
$text['label-switch']['de-at'] = "Switch"; //copied from de-de
$text['label-switch']['de-ch'] = "Switch"; //copied from de-de
$text['label-switch']['de-de'] = "Switch";
$text['label-switch']['es-cl'] = "Cambiar";
$text['label-switch']['es-mx'] = "Cambiar"; //copied from es-cl
$text['label-switch']['fr-ca'] = "Interrupteur"; //copied from fr-fr
$text['label-switch']['fr-fr'] = "Interrupteur";
$text['label-switch']['he-il'] = "החלף";
$text['label-switch']['it-it'] = "Switch";
$text['label-switch']['nl-nl'] = "Centrale";
$text['label-switch']['pl-pl'] = "Przełącznik";
$text['label-switch']['pt-br'] = "Interruptor"; //copied from pt-pt
$text['label-switch']['pt-pt'] = "Interruptor";
$text['label-switch']['ro-ro'] = "Intrerupator";
$text['label-switch']['ru-ru'] = "FreeSwitch";
$text['label-switch']['sv-se'] = "Switch";
$text['label-switch']['uk-ua'] = "перемикач";
$text['label-switch']['zh-cn'] = "转变";
$text['label-switch']['ja-jp'] = "スイッチ";
$text['label-switch']['ko-kr'] = "스위치";

$text['label-shell']['en-us'] = "Shell";
$text['label-shell']['en-gb'] = "Shell";
$text['label-shell']['ar-eg'] = "Coajă";
$text['label-shell']['de-at'] = "Shell"; //copied from de-de
$text['label-shell']['de-ch'] = "Shell"; //copied from de-de
$text['label-shell']['de-de'] = "Shell";
$text['label-shell']['es-cl'] = "Terminal de Comandos";
$text['label-shell']['es-mx'] = "Terminal de Comandos"; //copied from es-cl
$text['label-shell']['fr-ca'] = "Commande Shell"; //copied from fr-fr
$text['label-shell']['fr-fr'] = "Commande Shell";
$text['label-shell']['he-il'] = "صدَفَة";
$text['label-shell']['it-it'] = "Shell";
$text['label-shell']['nl-nl'] = "Shell";
$text['label-shell']['pl-pl'] = "Powłoka (shell)";
$text['label-shell']['pt-br'] = "Comando Shell ";
$text['label-shell']['pt-pt'] = "Comando Shell";
$text['label-shell']['ro-ro'] = "Coajă";
$text['label-shell']['ru-ru'] = "Консоль";
$text['label-shell']['sv-se'] = "Shell";
$text['label-shell']['uk-ua'] = "Консоль";
$text['label-shell']['zh-cn'] = "壳";
$text['label-shell']['ja-jp'] = "シェル";
$text['label-shell']['ko-kr'] = "껍데기";

$text['label-results']['en-us'] = "Results";
$text['label-results']['en-gb'] = "Results";
$text['label-results']['ar-eg'] = "نتائج";
$text['label-results']['de-at'] = "Ergebnisse"; //copied from de-de
$text['label-results']['de-ch'] = "Ergebnisse"; //copied from de-de
$text['label-results']['de-de'] = "Ergebnisse";
$text['label-results']['es-cl'] = "Resultados";
$text['label-results']['es-mx'] = "Resultados"; //copied from es-cl
$text['label-results']['fr-ca'] = "Résultats"; //copied from fr-fr
$text['label-results']['fr-fr'] = "Résultats";
$text['label-results']['he-il'] = "תוצאות";
$text['label-results']['it-it'] = "Risultati";
$text['label-results']['nl-nl'] = "Resultaten";
$text['label-results']['pl-pl'] = "Rezultaty";
$text['label-results']['pt-br'] = "Resultados"; //copied from pt-pt
$text['label-results']['pt-pt'] = "Resultados";
$text['label-results']['ro-ro'] = "Rezultate";
$text['label-results']['ru-ru'] = "Результаты";
$text['label-results']['sv-se'] = "Resultat";
$text['label-results']['uk-ua'] = "Результати";
$text['label-results']['zh-cn'] = "结果";
$text['label-results']['ja-jp'] = "結果";
$text['label-results']['ko-kr'] = "결과";

$text['label-result_type']['en-us'] = "Result";
$text['label-result_type']['en-gb'] = "Result";
$text['label-result_type']['ar-eg'] = "Rezultate";
$text['label-result_type']['de-at'] = "Ergebnis"; //copied from de-de
$text['label-result_type']['de-ch'] = "Ergebnis"; //copied from de-de
$text['label-result_type']['de-de'] = "Ergebnis";
$text['label-result_type']['es-cl'] = "Resultado";
$text['label-result_type']['es-mx'] = "Resultado"; //copied from es-cl
$text['label-result_type']['fr-ca'] = "Résultat"; //copied from fr-fr
$text['label-result_type']['fr-fr'] = "Résultat";
$text['label-result_type']['he-il'] = "תוֹצָאָה";
$text['label-result_type']['it-it'] = "Risultato";
$text['label-result_type']['nl-nl'] = "Resultaat";
$text['label-result_type']['pl-pl'] = "Rezultat";
$text['label-result_type']['pt-br'] = "Resultado"; //copied from pt-pt
$text['label-result_type']['pt-pt'] = "Resultado";
$text['label-result_type']['ro-ro'] = "Rezultate";
$text['label-result_type']['ru-ru'] = "Результат";
$text['label-result_type']['sv-se'] = "Resultat";
$text['label-result_type']['uk-ua'] = "Результат";
$text['label-result_type']['zh-cn'] = "结果";
$text['label-result_type']['ja-jp'] = "結果";
$text['label-result_type']['ko-kr'] = "결과";

$text['label-response']['en-us'] = "Response";
$text['label-response']['en-gb'] = "Response";
$text['label-response']['ar-eg'] = "إجابة";
$text['label-response']['de-at'] = "Antwort"; //copied from de-de
$text['label-response']['de-ch'] = "Antwort"; //copied from de-de
$text['label-response']['de-de'] = "Antwort";
$text['label-response']['es-cl'] = "Respuesta";
$text['label-response']['es-mx'] = "Respuesta"; //copied from es-cl
$text['label-response']['fr-ca'] = "Réponse"; //copied from fr-fr
$text['label-response']['fr-fr'] = "Réponse";
$text['label-response']['he-il'] = "תְגוּבָה";
$text['label-response']['it-it'] = "Risposta";
$text['label-response']['nl-nl'] = "Antwoord";
$text['label-response']['pl-pl'] = "Odpowiedź";
$text['label-response']['pt-br'] = "Resposta"; //copied from pt-pt
$text['label-response']['pt-pt'] = "Resposta";
$text['label-response']['ro-ro'] = "Raspuns";
$text['label-response']['ru-ru'] = "Ответ";
$text['label-response']['sv-se'] = "Respons";
$text['label-response']['uk-ua'] = "Відповідь";
$text['label-response']['zh-cn'] = "回复";
$text['label-response']['ja-jp'] = "応答";
$text['label-response']['ko-kr'] = "응답";

$text['label-reset']['en-us'] = "Reset";
$text['label-reset']['en-gb'] = "Reset";
$text['label-reset']['ar-eg'] = "إعادة تعيين";
$text['label-reset']['de-at'] = "Zurücksetzen"; //copied from de-de
$text['label-reset']['de-ch'] = "Zurücksetzen"; //copied from de-de
$text['label-reset']['de-de'] = "Zurücksetzen";
$text['label-reset']['es-cl'] = "Reajustar";
$text['label-reset']['es-mx'] = "Reajustar"; //copied from es-cl
$text['label-reset']['fr-ca'] = "Remettre"; //copied from fr-fr
$text['label-reset']['fr-fr'] = "Remettre";
$text['label-reset']['he-il'] = "אפס";
$text['label-reset']['it-it'] = "Resetta";
$text['label-reset']['nl-nl'] = "Reset";
$text['label-reset']['pl-pl'] = "Resetuj";
$text['label-reset']['pt-br'] = "Restabelecer"; //copied from pt-pt
$text['label-reset']['pt-pt'] = "Restabelecer";
$text['label-reset']['ro-ro'] = "Inițializare";
$text['label-reset']['ru-ru'] = "Сбросить";
$text['label-reset']['sv-se'] = "Återställ";
$text['label-reset']['uk-ua'] = "Скинути";
$text['label-reset']['zh-cn'] = "重置";
$text['label-reset']['ja-jp'] = "リセット";
$text['label-reset']['ko-kr'] = "초기화";

$text['label-records']['en-us'] = "Records";
$text['label-records']['en-gb'] = "Records";
$text['label-records']['ar-eg'] = "السجلات";
$text['label-records']['de-at'] = "Einträge"; //copied from de-de
$text['label-records']['de-ch'] = "Einträge"; //copied from de-de
$text['label-records']['de-de'] = "Einträge";
$text['label-records']['es-cl'] = "Archivos";
$text['label-records']['es-mx'] = "Archivos"; //copied from es-cl
$text['label-records']['fr-ca'] = "Enregistrements"; //copied from fr-fr
$text['label-records']['fr-fr'] = "Enregistrements";
$text['label-records']['he-il'] = "שיאים";
$text['label-records']['it-it'] = "Dati";
$text['label-records']['nl-nl'] = "Vastlegging";
$text['label-records']['pl-pl'] = "Dokumentacja";
$text['label-records']['pt-br'] = "Registros"; //copied from pt-pt
$text['label-records']['pt-pt'] = "Registros";
$text['label-records']['ro-ro'] = "Înregistrări";
$text['label-records']['ru-ru'] = "Записи";
$text['label-records']['sv-se'] = "Uppgifter";
$text['label-records']['uk-ua'] = "документація";
$text['label-records']['zh-cn'] = "记录";
$text['label-records']['ja-jp'] = "記録";
$text['label-records']['ko-kr'] = "기록";

$text['label-sql']['en-us'] = "SQL";
$text['label-sql']['en-gb'] = "SQL";
$text['label-sql']['ar-eg'] = "SQL";
$text['label-sql']['de-at'] = "SQL"; //copied from de-de
$text['label-sql']['de-ch'] = "SQL"; //copied from de-de
$text['label-sql']['de-de'] = "SQL";
$text['label-sql']['es-cl'] = "SQL";
$text['label-sql']['es-mx'] = "SQL"; //copied from es-cl
$text['label-sql']['fr-ca'] = "SQL"; //copied from fr-fr
$text['label-sql']['fr-fr'] = "SQL";
$text['label-sql']['he-il'] = "SQL";
$text['label-sql']['it-it'] = "SQL";
$text['label-sql']['nl-nl'] = "SQL";
$text['label-sql']['pl-pl'] = "SQL";
$text['label-sql']['pt-br'] = "SQL"; //copied from pt-pt
$text['label-sql']['pt-pt'] = "SQL";
$text['label-sql']['ro-ro'] = "SQL";
$text['label-sql']['ru-ru'] = "SQL";
$text['label-sql']['sv-se'] = "SQL";
$text['label-sql']['uk-ua'] = "SQL";
$text['label-sql']['zh-cn'] = "SQL";
$text['label-sql']['ja-jp'] = "SQL";
$text['label-sql']['ko-kr'] = "SQL";

$text['label-php']['en-us'] = "PHP";
$text['label-php']['en-gb'] = "PHP";
$text['label-php']['ar-eg'] = "PHP";
$text['label-php']['de-at'] = "PHP"; //copied from de-de
$text['label-php']['de-ch'] = "PHP"; //copied from de-de
$text['label-php']['de-de'] = "PHP";
$text['label-php']['es-cl'] = "Comando PHP";
$text['label-php']['es-mx'] = "Comando PHP"; //copied from es-cl
$text['label-php']['fr-ca'] = "Commande PHP"; //copied from fr-fr
$text['label-php']['fr-fr'] = "Commande PHP";
$text['label-php']['he-il'] = "PHP";
$text['label-php']['it-it'] = "PHP";
$text['label-php']['nl-nl'] = "PHP";
$text['label-php']['pl-pl'] = "PHP";
$text['label-php']['pt-br'] = "Comandos PHP ";
$text['label-php']['pt-pt'] = "Comandos PHP";
$text['label-php']['ro-ro'] = "PHP";
$text['label-php']['ru-ru'] = "Команды PHP";
$text['label-php']['sv-se'] = "PHP";
$text['label-php']['uk-ua'] = "PHP";
$text['label-php']['zh-cn'] = "PHP";
$text['label-php']['ja-jp'] = "PHP";
$text['label-php']['ko-kr'] = "PHP";

$text['label-execute']['en-us'] = "Execute Command";
$text['label-execute']['en-gb'] = "Execute Command";
$text['label-execute']['ar-eg'] = "تنفيذ الأوامر";
$text['label-execute']['de-at'] = "Befehl Ausführen"; //copied from de-de
$text['label-execute']['de-ch'] = "Befehl Ausführen"; //copied from de-de
$text['label-execute']['de-de'] = "Befehl Ausführen";
$text['label-execute']['es-cl'] = "Ejecutar Comando";
$text['label-execute']['es-mx'] = "Ejecutar Comando"; //copied from es-cl
$text['label-execute']['fr-ca'] = "Executer la Commande"; //copied from fr-fr
$text['label-execute']['fr-fr'] = "Executer la Commande";
$text['label-execute']['he-il'] = "בצע פקודה";
$text['label-execute']['it-it'] = "Esegui Comando";
$text['label-execute']['nl-nl'] = "Voer commando uit";
$text['label-execute']['pl-pl'] = "Wykonywanie poleceń";
$text['label-execute']['pt-br'] = "Executar";
$text['label-execute']['pt-pt'] = "Executar Comando";
$text['label-execute']['ro-ro'] = "Executați comanda";
$text['label-execute']['ru-ru'] = "Выполнить команду";
$text['label-execute']['sv-se'] = "Utför Kommando";
$text['label-execute']['uk-ua'] = "Виконання команд";
$text['label-execute']['zh-cn'] = "执行命令";
$text['label-execute']['ja-jp'] = "コマンドの実行";
$text['label-execute']['ko-kr'] = "명령 실행";

$text['label-error']['en-us'] = "Error";
$text['label-error']['en-gb'] = "Error";
$text['label-error']['ar-eg'] = "خطأ";
$text['label-error']['de-at'] = "Fehler"; //copied from de-de
$text['label-error']['de-ch'] = "Fehler"; //copied from de-de
$text['label-error']['de-de'] = "Fehler";
$text['label-error']['es-cl'] = "Error";
$text['label-error']['es-mx'] = "Error"; //copied from es-cl
$text['label-error']['fr-ca'] = "Erreur"; //copied from fr-fr
$text['label-error']['fr-fr'] = "Erreur";
$text['label-error']['he-il'] = "שְׁגִיאָה";
$text['label-error']['it-it'] = "Errore";
$text['label-error']['nl-nl'] = "Fout";
$text['label-error']['pl-pl'] = "Błąd";
$text['label-error']['pt-br'] = "Erro"; //copied from pt-pt
$text['label-error']['pt-pt'] = "Erro";
$text['label-error']['ro-ro'] = "Eroare";
$text['label-error']['ru-ru'] = "Ошибка";
$text['label-error']['sv-se'] = "Fel";
$text['label-error']['uk-ua'] = "Помилка";
$text['label-error']['zh-cn'] = "错误";
$text['label-error']['ja-jp'] = "エラー";
$text['label-error']['ko-kr'] = "오류";

$text['header-databases']['en-us'] = "Databases";
$text['header-databases']['en-gb'] = "Databases";
$text['header-databases']['ar-eg'] = "قواعد بيانات";
$text['header-databases']['de-at'] = "Datenbanken"; //copied from de-de
$text['header-databases']['de-ch'] = "Datenbanken"; //copied from de-de
$text['header-databases']['de-de'] = "Datenbanken";
$text['header-databases']['es-cl'] = "Bases de datos";
$text['header-databases']['es-mx'] = "Bases de datos"; //copied from es-cl
$text['header-databases']['fr-ca'] = "Bases de données"; //copied from fr-fr
$text['header-databases']['fr-fr'] = "Bases de données";
$text['header-databases']['he-il'] = "מאגרי מידע";
$text['header-databases']['it-it'] = "Database";
$text['header-databases']['nl-nl'] = "Databases";
$text['header-databases']['pl-pl'] = "Bazy danych";
$text['header-databases']['pt-br'] = "Base de dados";
$text['header-databases']['pt-pt'] = "Bases de Dados";
$text['header-databases']['ro-ro'] = "Baze de date";
$text['header-databases']['ru-ru'] = "База Данных";
$text['header-databases']['sv-se'] = "Databaser";
$text['header-databases']['uk-ua'] = "Бази даних";
$text['header-databases']['zh-cn'] = "数据库";
$text['header-databases']['ja-jp'] = "データベース";
$text['header-databases']['ko-kr'] = "데이터베이스";

$text['description-switch']['en-us'] = "Switch CLI. View valid commands with: 'help'.";
$text['description-switch']['en-gb'] = "Switch CLI. View valid commands with: 'help'.";
$text['description-switch']['ar-eg'] = 'تبديل CLI. عرض الأوامر الصالحة باستخدام: "مساعدة".';
$text['description-switch']['de-at'] = "Um eine Liste der gültigen Befehle zu erhalten tippen Sie: 'help'"; //copied from de-de
$text['description-switch']['de-ch'] = "Um eine Liste der gültigen Befehle zu erhalten tippen Sie: 'help'"; //copied from de-de
$text['description-switch']['de-de'] = "Um eine Liste der gültigen Befehle zu erhalten tippen Sie: 'help'";
$text['description-switch']['es-cl'] = "Para un listado de comandos válidos use: help";
$text['description-switch']['es-mx'] = "Para un listado de comandos válidos use: help"; //copied from es-cl
$text['description-switch']['fr-ca'] = "Pour la liste des commandes valides, utiliser : help"; //copied from fr-fr
$text['description-switch']['fr-fr'] = "Pour la liste des commandes valides, utiliser : help";
$text['description-switch']['he-il'] = "החלף CLI. הצג פקודות חוקיות עם: 'עזרה'.";
$text['description-switch']['it-it'] = "CLI Sqitch Telefonico. Visualizza comandi validi con: 'help'.";
$text['description-switch']['nl-nl'] = "Centrale CLI, bekijk geldige commando's met: 'help'.";
$text['description-switch']['pl-pl'] = "Aby uzyskać listę poprawnych poleceń użyj pomocy";
$text['description-switch']['pt-br'] = "Para verificar a lista de comandos válidos utilize: Ajuda";
$text['description-switch']['pt-pt'] = "Para uma lista dos comandos válidos utilize: help";
$text['description-switch']['ro-ro'] = "Comutați CLI. Vizualizați comenzile valide cu: „ajutor”.";
$text['description-switch']['ru-ru'] = "Switch CLI.Для получения списка доступных команд, используйте:'help'.";
$text['description-switch']['sv-se'] = "För en lista med giltiga kommandon använd: help";
$text['description-switch']['uk-ua'] = "Для перегляду списку команд виконайте команду: help";
$text['description-switch']['zh-cn'] = "切换 CLI。 使用“help”查看有效命令。";
$text['description-switch']['ja-jp'] = "CLIを切り替えます。 有効なコマンドを表示するには、「help」を使用します。";
$text['description-switch']['ko-kr'] = "CLI를 전환하세요. 'help'를 사용하여 유효한 명령을 확인하세요.";

$text['description-shell']['en-us'] = "Execute system commands.";
$text['description-shell']['en-gb'] = "Execute system commands.";
$text['description-shell']['ar-eg'] = "نفذ أوامر النظام.";
$text['description-shell']['de-at'] = "System Befehle ausführen"; //copied from de-de
$text['description-shell']['de-ch'] = "System Befehle ausführen"; //copied from de-de
$text['description-shell']['de-de'] = "System Befehle ausführen";
$text['description-shell']['es-cl'] = "Comandos de sistema";
$text['description-shell']['es-mx'] = "Comandos de sistema"; //copied from es-cl
$text['description-shell']['fr-ca'] = "Commande Système"; //copied from fr-fr
$text['description-shell']['fr-fr'] = "Commande Système";
$text['description-shell']['he-il'] = "בצע פקודות מערכת.";
$text['description-shell']['it-it'] = "Esegui comandi di sistema.";
$text['description-shell']['nl-nl'] = "Voer systeem commando's uit.";
$text['description-shell']['pl-pl'] = "Polecenia systemowe.";
$text['description-shell']['pt-br'] = "Comando do sistema";
$text['description-shell']['pt-pt'] = "Comandos do sistema.";
$text['description-shell']['ro-ro'] = "Executați comenzile sistemului.";
$text['description-shell']['ru-ru'] = "Выполните системные команды.";
$text['description-shell']['sv-se'] = "System Kommandon.";
$text['description-shell']['uk-ua'] = "Системні команди";
$text['description-shell']['zh-cn'] = "执行系统命令。";
$text['description-shell']['ja-jp'] = "システムコマンドを実行します。";
$text['description-shell']['ko-kr'] = "시스템 명령을 실행합니다.";

$text['description-sql']['en-us'] = "Execute statements against the database.";
$text['description-sql']['en-gb'] = "Execute statements against the database.";
$text['description-sql']['ar-eg'] = "تنفيذ العبارات على قاعدة البيانات.";
$text['description-sql']['de-at'] = "Abfragen gegen die Datenbank ausführen."; //copied from de-de
$text['description-sql']['de-ch'] = "Abfragen gegen die Datenbank ausführen."; //copied from de-de
$text['description-sql']['de-de'] = "Abfragen gegen die Datenbank ausführen.";
$text['description-sql']['es-cl'] = "Ejecutar instrucciones de consulta contra la base de datos.";
$text['description-sql']['es-mx'] = "Ejecutar instrucciones de consulta contra la base de datos."; //copied from es-cl
$text['description-sql']['fr-ca'] = "Exécuter les instructions de requête contre la base de données."; //copied from fr-fr
$text['description-sql']['fr-fr'] = "Exécuter les instructions de requête contre la base de données.";
$text['description-sql']['he-il'] = "בצע הצהרות כנגד מסד הנתונים.";
$text['description-sql']['it-it'] = "Esegui istruzioni sul database.";
$text['description-sql']['nl-nl'] = "Voer instructies uit op de database.";
$text['description-sql']['pl-pl'] = "Wykonać polecenie zapytania do bazy danych.";
$text['description-sql']['pt-br'] = "Executar instruções de consulta no banco de dados."; //copied from pt-pt
$text['description-sql']['pt-pt'] = "Executar instruções de consulta no banco de dados.";
$text['description-sql']['ro-ro'] = "Executați instrucțiuni în baza de date.";
$text['description-sql']['ru-ru'] = "Выполнение запросов для базы данных.";
$text['description-sql']['sv-se'] = "Utför fråge uttalanden mot databasen.";
$text['description-sql']['uk-ua'] = "Виконання операторів запитів до бази даних.";
$text['description-sql']['zh-cn'] = "针对数据库执行语句。";
$text['description-sql']['ja-jp'] = "データベースに対してステートメントを実行します。";
$text['description-sql']['ko-kr'] = "데이터베이스에 대해 명령문을 실행합니다.";

$text['description-php']['en-us'] = "Execute PHP commands.  See: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";
$text['description-php']['en-gb'] = "Execute PHP commands.  See: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";
$text['description-php']['ar-eg'] = "تنفيذ أوامر PHP. راجع: <a href='http://php.net/manual/' target='_blank'>دليل PHP</a>";
$text['description-php']['de-at'] = "PHP Befehle ausführen. Benutzen Sie folgenden Link als PHP Referenz: <a href='http://php.net/manual/>PHP Manual</a>"; //copied from de-de
$text['description-php']['de-ch'] = "PHP Befehle ausführen. Benutzen Sie folgenden Link als PHP Referenz: <a href='http://php.net/manual/>PHP Manual</a>"; //copied from de-de
$text['description-php']['de-de'] = "PHP Befehle ausführen. Benutzen Sie folgenden Link als PHP Referenz: <a href='http://php.net/manual/>PHP Manual</a>";
$text['description-php']['es-cl'] = "Utilice el siguiente enlace como referencia para PHP: <a href='http://php.net/manual/' target='_blank'>Manual PHP</a>";
$text['description-php']['es-mx'] = "Utilice el siguiente enlace como referencia para PHP: <a href='http://php.net/manual/' target='_blank'>Manual PHP</a>"; //copied from es-cl
$text['description-php']['fr-ca'] = "Utiliser le lien suivant comme référence pour le PHP: <a href='http://php.net/manual/' target='_blank'>Manuel PHP</a>"; //copied from fr-fr
$text['description-php']['fr-fr'] = "Utiliser le lien suivant comme référence pour le PHP: <a href='http://php.net/manual/' target='_blank'>Manuel PHP</a>";
$text['description-php']['he-il'] = "בצע פקודות PHP. ראה: <a href='http://php.net/manual/' target='_blank'>מדריך PHP</a>";
$text['description-php']['it-it'] = "Esegue comandi PHP. Vedi: <a href='http://php.net/manual/' target='_blank'>Manuale PHP</a>";
$text['description-php']['nl-nl'] = "Voer PHP commando's uit. Zie: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";
$text['description-php']['pl-pl'] = "Aby użyć odniesienia do PHP kliknij na ten link: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";
$text['description-php']['pt-br'] = "Utilize a ligação seguinte como referência para o PHP: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>"; //copied from pt-pt
$text['description-php']['pt-pt'] = "Utilize a ligação seguinte como referência para o PHP: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";
$text['description-php']['ro-ro'] = "Executați comenzi PHP. Consultați: <a href='http://php.net/manual/' target='_blank'>Manual PHP</a>";
$text['description-php']['ru-ru'] = "Выполнение PHP команд. Смотрите: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";
$text['description-php']['sv-se'] = "Använd följande länk som en referens gällande PHP: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";
$text['description-php']['uk-ua'] = "Посилання на довідку PHP: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";
$text['description-php']['zh-cn'] = "执行 PHP 命令。 请参阅：<a href='http://php.net/manual/' target='_blank'>PHP 手册</a>";
$text['description-php']['ja-jp'] = "PHPコマンドを実行します。 参照先: <a href='http://php.net/manual/' target='_blank'>PHP マニュアル</a>";
$text['description-php']['ko-kr'] = "PHP 명령을 실행합니다. 참조: <a href='http://php.net/manual/' target='_blank'>PHP 매뉴얼</a>";

$text['description-sql_query']['en-us'] = "Provides a conventient way to execute SQL commands.";
$text['description-sql_query']['en-gb'] = "Provides a conventient way to execute SQL commands.";
$text['description-sql_query']['ar-eg'] = "يوفر طريقة ملائمة لتنفيذ أوامر SQL.";
$text['description-sql_query']['de-at'] = "Bietet die Möglichkeit SQL Befehle auszuführen."; //copied from de-de
$text['description-sql_query']['de-ch'] = "Bietet die Möglichkeit SQL Befehle auszuführen."; //copied from de-de
$text['description-sql_query']['de-de'] = "Bietet die Möglichkeit SQL Befehle auszuführen.";
$text['description-sql_query']['es-cl'] = "Provee un modo conveniente de ejecutar comandos de sistema, PHP o del switch.";
$text['description-sql_query']['es-mx'] = "Provee un modo conveniente de ejecutar comandos de sistema, PHP o del switch."; //copied from es-cl
$text['description-sql_query']['fr-ca'] = "Fournir un moyen pour executer des commandes système, PHP et switch. "; //copied from fr-fr
$text['description-sql_query']['fr-fr'] = "Fournir un moyen pour executer des commandes système, PHP et switch. ";
$text['description-sql_query']['he-il'] = "מספק דרך נוחה לביצוע פקודות SQL.";
$text['description-sql_query']['it-it'] = "Fornisce un facile sistema per eseguire i comandi di sistema, PHP, SQL e dello Switch.";
$text['description-sql_query']['nl-nl'] = "Voorzie in een makkelijke manier om opdrachten uit te voeren voor: systeem, PHP, centrale en SQL";
$text['description-sql_query']['pl-pl'] = "Ta funkcja zapewnia dogodny sposób wykonywania poleceń systemowych, PHP oraz switch.";
$text['description-sql_query']['pt-br'] = "Utilize facilmente a execução de comandos do sistema, PHP e switch ";
$text['description-sql_query']['pt-pt'] = "Oferece uma maneira fácil de executar comandos de sistema, PHP, e switch.";
$text['description-sql_query']['ro-ro'] = "Oferă o modalitate convenabilă de a executa comenzi SQL.";
$text['description-sql_query']['ru-ru'] = "Обеспечивает удобный способ выполнения команд системы, PHP, FreeSwitch и SQL.";
$text['description-sql_query']['sv-se'] = "Erbjuder ett smidigt sätt att köra system, PHP och switch kommandon.";
$text['description-sql_query']['uk-ua'] = "Забезпечує зручний спосіб виконати команди PHP, switch, а також системні команди";
$text['description-sql_query']['zh-cn'] = "提供了一种执行 SQL 命令的便捷方法。";
$text['description-sql_query']['ja-jp'] = "SQL コマンドを実行する便利な方法を提供します。";
$text['description-sql_query']['ko-kr'] = "SQL 명령을 실행하는 편리한 방법을 제공합니다.";

$text['description-databases']['en-us'] = "Select the database to execute SQL query statements against.";
$text['description-databases']['en-gb'] = "Select the database to execute SQL query statements against.";
$text['description-databases']['ar-eg'] = "حدد قاعدة البيانات لتنفيذ عبارات استعلام SQL مقابلها.";
$text['description-databases']['de-at'] = "Wählen Sie die Datenbank für die SQL Abfrage aus."; //copied from de-de
$text['description-databases']['de-ch'] = "Wählen Sie die Datenbank für die SQL Abfrage aus."; //copied from de-de
$text['description-databases']['de-de'] = "Wählen Sie die Datenbank für die SQL Abfrage aus.";
$text['description-databases']['es-cl'] = "Seleccione la base de datos para ejecutar la consulta SQL.";
$text['description-databases']['es-mx'] = "Seleccione la base de datos para ejecutar la consulta SQL."; //copied from es-cl
$text['description-databases']['fr-ca'] = "Choisir la base de données utilisée par la requête SQL."; //copied from fr-fr
$text['description-databases']['fr-fr'] = "Choisir la base de données utilisée par la requête SQL.";
$text['description-databases']['he-il'] = "בחר את מסד הנתונים שעבורו יש לבצע הצהרות שאילתת SQL.";
$text['description-databases']['it-it'] = "Selezionare il database sul quale eseguire query SQL.";
$text['description-databases']['nl-nl'] = "Kies de database waatop het SQL statment uitgevoerd moet worden.";
$text['description-databases']['pl-pl'] = "Informacje o bazie danych.";
$text['description-databases']['pt-br'] = "Informações sobre a base de dados";
$text['description-databases']['pt-pt'] = "Escolha a base de dados a utilizar.";
$text['description-databases']['ro-ro'] = "Selectați baza de date pentru a executa instrucțiunile de interogare SQL.";
$text['description-databases']['ru-ru'] = "Выберите базу данных для выполнения SQL-запросов.";
$text['description-databases']['sv-se'] = "Välj databas att använda för SQL Fråga.";
$text['description-databases']['uk-ua'] = "Інформація про базу даних.";
$text['description-databases']['zh-cn'] = "选择要执行 SQL 查询语句的数据库。";
$text['description-databases']['ja-jp'] = "SQL クエリ ステートメントを実行するデータベースを選択します。";
$text['description-databases']['ko-kr'] = "SQL 쿼리 문을 실행할 데이터베이스를 선택합니다.";

$text['button-select_database']['en-us'] = "Select Database";
$text['button-select_database']['en-gb'] = "Select Database";
$text['button-select_database']['ar-eg'] = "حدد قاعدة البيانات";
$text['button-select_database']['de-at'] = "Datenbank auswählen"; //copied from de-de
$text['button-select_database']['de-ch'] = "Datenbank auswählen"; //copied from de-de
$text['button-select_database']['de-de'] = "Datenbank auswählen";
$text['button-select_database']['es-cl'] = "Seleccionar Base de Datos";
$text['button-select_database']['es-mx'] = "Seleccionar Base de Datos"; //copied from es-cl
$text['button-select_database']['fr-ca'] = "Choisir la Base de données"; //copied from fr-fr
$text['button-select_database']['fr-fr'] = "Choisir la Base de données";
$text['button-select_database']['he-il'] = "בחר מסד נתונים";
$text['button-select_database']['it-it'] = "Selezionare Database";
$text['button-select_database']['nl-nl'] = "Kies database";
$text['button-select_database']['pl-pl'] = "Wybierz bazę danych";
$text['button-select_database']['pt-br'] = "Selecionar base de dados";
$text['button-select_database']['pt-pt'] = "Seleccionar Base de Dados";
$text['button-select_database']['ro-ro'] = "Selectați Baza de date";
$text['button-select_database']['ru-ru'] = "Выберите Базу Данных";
$text['button-select_database']['sv-se'] = "Välj Databas";
$text['button-select_database']['uk-ua'] = "Вибрати БД";
$text['button-select_database']['zh-cn'] = "选择数据库";
$text['button-select_database']['ja-jp'] = "データベースの選択";
$text['button-select_database']['ko-kr'] = "데이터베이스 선택";

$text['button-manage']['en-us'] = "Manage";
$text['button-manage']['en-gb'] = "Manage";
$text['button-manage']['ar-eg'] = "يدير";
$text['button-manage']['de-at'] = "Verwalten"; //copied from de-de
$text['button-manage']['de-ch'] = "Verwalten"; //copied from de-de
$text['button-manage']['de-de'] = "Verwalten";
$text['button-manage']['es-cl'] = "Administrar";
$text['button-manage']['es-mx'] = "Administrar"; //copied from es-cl
$text['button-manage']['fr-ca'] = "Gérer"; //copied from fr-fr
$text['button-manage']['fr-fr'] = "Gérer";
$text['button-manage']['he-il'] = "לנהל";
$text['button-manage']['it-it'] = "Gestione";
$text['button-manage']['nl-nl'] = "Beheer";
$text['button-manage']['pl-pl'] = "Zarządzaj";
$text['button-manage']['pt-br'] = "Gerenciar";
$text['button-manage']['pt-pt'] = "Gerir";
$text['button-manage']['ro-ro'] = "Administra";
$text['button-manage']['ru-ru'] = "Управление";
$text['button-manage']['sv-se'] = "Hantera";
$text['button-manage']['uk-ua'] = "Керувати";
$text['button-manage']['zh-cn'] = "管理";
$text['button-manage']['ja-jp'] = "管理";
$text['button-manage']['ko-kr'] = "관리하다";

$text['button-backup']['en-us'] = "Backup";
$text['button-backup']['en-gb'] = "Backup";
$text['button-backup']['ar-eg'] = "دعم";
$text['button-backup']['de-at'] = "Sichern"; //copied from de-de
$text['button-backup']['de-ch'] = "Sichern"; //copied from de-de
$text['button-backup']['de-de'] = "Sichern";
$text['button-backup']['es-cl'] = "Respaldar";
$text['button-backup']['es-mx'] = "Respaldar"; //copied from es-cl
$text['button-backup']['fr-ca'] = "Sauvegarder"; //copied from fr-fr
$text['button-backup']['fr-fr'] = "Sauvegarder";
$text['button-backup']['he-il'] = "גיבוי";
$text['button-backup']['it-it'] = "Backup";
$text['button-backup']['nl-nl'] = "Backup";
$text['button-backup']['pl-pl'] = "Kopia Zapasowa";
$text['button-backup']['pt-br'] = "Backup"; //copied from pt-pt
$text['button-backup']['pt-pt'] = "Backup";
$text['button-backup']['ro-ro'] = "Backup";
$text['button-backup']['ru-ru'] = "Резервное Копирование";
$text['button-backup']['sv-se'] = "Backup";
$text['button-backup']['uk-ua'] = "Резервна копія";
$text['button-backup']['zh-cn'] = "备份";
$text['button-backup']['ja-jp'] = "バックアップ";
$text['button-backup']['ko-kr'] = "지원";

$text['label-clip-library']['en-us'] = "Clip Library";
$text['label-clip-library']['ar-eg'] = "المكتبة";
$text['label-clip-library']['de-at'] = "Clip Bibliothek";
$text['label-clip-library']['de-ch'] = "Clip Bibliothek";
$text['label-clip-library']['de-de'] = "Clip Bibliothek";
$text['label-clip-library']['es-cl'] = "Librería de Clips";
$text['label-clip-library']['es-mx'] = "Librería de Clips";
$text['label-clip-library']['fr-ca'] = "Clip Libraries";
$text['label-clip-library']['fr-fr'] = "Clip Libraries";
$text['label-clip-library']['he-il'] = "ספריית קליפ";
$text['label-clip-library']['it-it'] = "Libreria Clip";
$text['label-clip-library']['nl-nl'] = "Clip bibliotheek";
$text['label-clip-library']['pl-pl'] = "biblioteki";
$text['label-clip-library']['pt-br'] = "Biblioteca de Clips";
$text['label-clip-library']['pt-pt'] = "Biblioteca de Clips";
$text['label-clip-library']['ro-ro'] = "";
$text['label-clip-library']['ru-ru'] = "Библиотека клипов";
$text['label-clip-library']['sv-se'] = "Klipp Bibliotek";
$text['label-clip-library']['uk-ua'] = "Бібліотека кліпів";

$text['label-selected-clip']['en-us'] = "Selected Clip";
$text['label-selected-clip']['ar-eg'] = "مقطع مختار";
$text['label-selected-clip']['de-at'] = "Ausgewählter Clip";
$text['label-selected-clip']['de-ch'] = "Ausgewählter Clip";
$text['label-selected-clip']['de-de'] = "Ausgewählter Clip";
$text['label-selected-clip']['es-cl'] = "Clip Seleccionado";
$text['label-selected-clip']['es-mx'] = "Clip Seleccionado";
$text['label-selected-clip']['fr-ca'] = "Clip Sélectionné";
$text['label-selected-clip']['fr-fr'] = "Clip Sélectionné";
$text['label-selected-clip']['he-il'] = "נבחר קליפ";
$text['label-selected-clip']['it-it'] = "Clip Selezionate";
$text['label-selected-clip']['nl-nl'] = "Gekozen Clip";
$text['label-selected-clip']['pl-pl'] = "Wybrany Clip";
$text['label-selected-clip']['pt-br'] = "Clipe Selecionado";
$text['label-selected-clip']['pt-pt'] = "Clipe Selecionado";
$text['label-selected-clip']['ro-ro'] = "";
$text['label-selected-clip']['ru-ru'] = "Выбранный клип";
$text['label-selected-clip']['sv-se'] = "Valt Clip";
$text['label-selected-clip']['uk-ua'] = "Вибраний кліп";

$text['button-edit-clip']['en-us'] = "Edit Clip";
$text['button-edit-clip']['ar-eg'] = "مشبك التحرير";
$text['button-edit-clip']['de-at'] = "Clip bearbeiten";
$text['button-edit-clip']['de-ch'] = "Clip bearbeiten";
$text['button-edit-clip']['de-de'] = "Clip bearbeiten";
$text['button-edit-clip']['es-cl'] = "Editar Clip";
$text['button-edit-clip']['es-mx'] = "Editar Clip";
$text['button-edit-clip']['fr-ca'] = "Editer le Clip";
$text['button-edit-clip']['fr-fr'] = "Editer le Clip";
$text['button-edit-clip']['he-il'] = "Edit קליפ";
$text['button-edit-clip']['it-it'] = "Modifica Clip";
$text['button-edit-clip']['nl-nl'] = "Bewerk Clip";
$text['button-edit-clip']['pl-pl'] = "edit clip";
$text['button-edit-clip']['pt-br'] = "Editar Clip";
$text['button-edit-clip']['pt-pt'] = "Editar Clip";
$text['button-edit-clip']['ro-ro'] = "";
$text['button-edit-clip']['ru-ru'] = "Редактировать клип";
$text['button-edit-clip']['sv-se'] = "Ändra Klipp";
$text['button-edit-clip']['uk-ua'] = "Редагувати кліп";

$text['button-add-clip']['en-us'] = "Add Clip";
$text['button-add-clip']['ar-eg'] = "مشط";
$text['button-add-clip']['de-at'] = "Clip hinzufügen";
$text['button-add-clip']['de-ch'] = "Clip hinzufügen";
$text['button-add-clip']['de-de'] = "Clip hinzufügen";
$text['button-add-clip']['es-cl'] = "Agregar Clip";
$text['button-add-clip']['es-mx'] = "Agregar Clip";
$text['button-add-clip']['fr-ca'] = "Ajouter un Clip";
$text['button-add-clip']['fr-fr'] = "Ajouter un Clip";
$text['button-add-clip']['he-il'] = "הוסף קליפ";
$text['button-add-clip']['it-it'] = "Inserisci Clip";
$text['button-add-clip']['nl-nl'] = "Voeg Clip toe";
$text['button-add-clip']['pl-pl'] = "Addd Clip";
$text['button-add-clip']['pt-br'] = "Adicionar Clip";
$text['button-add-clip']['pt-pt'] = "Adicionar Clip";
$text['button-add-clip']['ro-ro'] = "";
$text['button-add-clip']['ru-ru'] = "Добавить клип";
$text['button-add-clip']['sv-se'] = "Lägg Till Klipp";
$text['button-add-clip']['uk-ua'] = "Додати кліп";


$text['label-folder']['en-us'] = "Folder:";
$text['label-folder']['ar-eg'] = "فولدر:";
$text['label-folder']['de-at'] = "Ordner:";
$text['label-folder']['de-ch'] = "Ordner:";
$text['label-folder']['de-de'] = "Ordner:";
$text['label-folder']['es-cl'] = "Carpeta:";
$text['label-folder']['es-mx'] = "Carpeta:";
$text['label-folder']['fr-ca'] = "Dossier:";
$text['label-folder']['fr-fr'] = "Dossier:";
$text['label-folder']['he-il'] = "מקור:";
$text['label-folder']['it-it'] = "Cartella:";
$text['label-folder']['nl-nl'] = "Map:";
$text['label-folder']['pl-pl'] = "folder: folder";
$text['label-folder']['pt-br'] = "Ficheiro:";
$text['label-folder']['pt-pt'] = "Ficheiro:";
$text['label-folder']['ro-ro'] = "";
$text['label-folder']['ru-ru'] = "Папка:";
$text['label-folder']['sv-se'] = "Mapp:";
$text['label-folder']['uk-ua'] = "Склад:";

$text['label-before-selection']['en-us'] = "Before Selection:";
$text['label-before-selection']['ar-eg'] = "قبل الاختيار:";
$text['label-before-selection']['de-at'] = "Vor der Auswahl:";
$text['label-before-selection']['de-ch'] = "Vor der Auswahl:";
$text['label-before-selection']['de-de'] = "Vor der Auswahl:";
$text['label-before-selection']['es-cl'] = "Antes de seleccionar:";
$text['label-before-selection']['es-mx'] = "Antes de seleccionar:";
$text['label-before-selection']['fr-ca'] = "Avant la Selection:";
$text['label-before-selection']['fr-fr'] = "Avant la Selection:";
$text['label-before-selection']['he-il'] = "לפני הבחירה:";
$text['label-before-selection']['it-it'] = "Precedente Selezione:";
$text['label-before-selection']['nl-nl'] = "Voor selectie:";
$text['label-before-selection']['pl-pl'] = "Przed wyborem";
$text['label-before-selection']['pt-br'] = "Antes da Selecção:";
$text['label-before-selection']['pt-pt'] = "Antes da Selecção:";
$text['label-before-selection']['ro-ro'] = "";
$text['label-before-selection']['ru-ru'] = "Перед выбором:";
$text['label-before-selection']['sv-se'] = "Före Val:";
$text['label-before-selection']['uk-ua'] = "До вибору:";

$text['label-after-selection']['en-us'] = "After Selection:";
$text['label-after-selection']['ar-eg'] = "بعد الاختيار:";
$text['label-after-selection']['de-at'] = "Nach der Auswahl:";
$text['label-after-selection']['de-ch'] = "Nach der Auswahl:";
$text['label-after-selection']['de-de'] = "Nach der Auswahl:";
$text['label-after-selection']['es-cl'] = "Despues de seleccionar:";
$text['label-after-selection']['es-mx'] = "Despues de seleccionar:";
$text['label-after-selection']['fr-ca'] = "Après la Selection:";
$text['label-after-selection']['fr-fr'] = "Après la Selection:";
$text['label-after-selection']['he-il'] = "לאחר הבחירה:";
$text['label-after-selection']['it-it'] = "Successiva Selezione:";
$text['label-after-selection']['nl-nl'] = "Na Selectie:";
$text['label-after-selection']['pl-pl'] = "Po wyborach:";
$text['label-after-selection']['pt-br'] = "Depois da Selecção:";
$text['label-after-selection']['pt-pt'] = "Depois da Selecção:";
$text['label-after-selection']['ro-ro'] = "";
$text['label-after-selection']['ru-ru'] = "После выбора:";
$text['label-after-selection']['sv-se'] = "Efter Val:";
$text['label-after-selection']['uk-ua'] = "Після вибору:";

$text['label-notes']['en-us'] = "Notes:";
$text['label-notes']['ar-eg'] = "الحواشي:";
$text['label-notes']['de-at'] = "Notiz:";
$text['label-notes']['de-ch'] = "Notiz:";
$text['label-notes']['de-de'] = "Notiz:";
$text['label-notes']['es-cl'] = "Notas:";
$text['label-notes']['es-mx'] = "Notas:";
$text['label-notes']['fr-ca'] = "Remarques:";
$text['label-notes']['fr-fr'] = "Remarques:";
$text['label-notes']['he-il'] = "הערות:";
$text['label-notes']['it-it'] = "Note:";
$text['label-notes']['nl-nl'] = "Notitie:";
$text['label-notes']['pl-pl'] = "Nota:";
$text['label-notes']['pt-br'] = "Notas:";
$text['label-notes']['pt-pt'] = "Notas:";
$text['label-notes']['ro-ro'] = "";
$text['label-notes']['ru-ru'] = "Заметки:";
$text['label-notes']['sv-se'] = "Noteringar:";
$text['label-notes']['uk-ua'] = "Примітки:";

$text['message-delete-clip']['en-us'] = "Are you sure you want to delete the selected clip?";
$text['message-delete-clip']['ar-eg'] = "هل أنت متأكد من أنك تريد حذف المقطع المختار؟";
$text['message-delete-clip']['de-at'] = "Sind Sie sicher, dass Sie den ausgewählten Clip löschen möchten?";
$text['message-delete-clip']['de-ch'] = "Sind Sie sicher, dass Sie den ausgewählten Clip löschen möchten?";
$text['message-delete-clip']['de-de'] = "Sind Sie sicher, dass Sie den ausgewählten Clip löschen möchten?";
$text['message-delete-clip']['es-cl'] = "¿Realmente desea eliminar el clip seleccionado?";
$text['message-delete-clip']['es-mx'] = "¿Realmente desea eliminar el clip seleccionado?";
$text['message-delete-clip']['fr-ca'] = "Etes-vous sûr de vouloir supprimer le CLIP sélectionné?";
$text['message-delete-clip']['fr-fr'] = "Etes-vous sûr de vouloir supprimer le CLIP sélectionné?";
$text['message-delete-clip']['he-il'] = "אתה בטוח שאתה רוצה למחוק את הסרטון שנבחר?";
$text['message-delete-clip']['it-it'] = "Sei sicuro di voler cancellare le clip selezionate?";
$text['message-delete-clip']['nl-nl'] = "Weet je zeker dat je de gekozen Clip wil verwijderen?";
$text['message-delete-clip']['pl-pl'] = "Czy chcesz usunąć wybrane klipy?";
$text['message-delete-clip']['pt-br'] = "Tem a certeza que pretende remover o clip seleccionado?";
$text['message-delete-clip']['pt-pt'] = "Tem a certeza que pretende remover o clip seleccionado?";
$text['message-delete-clip']['ro-ro'] = "";
$text['message-delete-clip']['ru-ru'] = "Вы действительно хотите удалить выбранный клип?";
$text['message-delete-clip']['sv-se'] = "Är du säker på att du vill radera det valda klippet?";
$text['message-delete-clip']['uk-ua'] = "Ви впевнені, що ви хочете видалити вибраний кліп?";


$text['message-give-up']['en-us'] = "Giving up :( Cannot create an XMLHTTP instance";
$text['message-give-up']['en-gb'] = "Giving up :( Cannot create an XMLHTTP instance";
$text['message-give-up']['ar-eg'] = ": لا يُمكن أن يُخلق مثال على ذلك";
$text['message-give-up']['de-at'] = "Vorgang abgebrochen :( Konnte XMLHTTP Instanz nich erzeugen";
$text['message-give-up']['de-ch'] = "Vorgang abgebrochen :( Konnte XMLHTTP Instanz nich erzeugen";
$text['message-give-up']['de-de'] = "Vorgang abgebrochen :( Konnte XMLHTTP Instanz nich erzeugen";
$text['message-give-up']['es-cl'] = "Cancelando, no se puede crear una instancia XMLHTTP";
$text['message-give-up']['es-mx'] = "Cancelando, no se puede crear una instancia XMLHTTP";
$text['message-give-up']['fr-ca'] = "Abandonner :( Ne peut pas créer un instance XMLHTTP";
$text['message-give-up']['fr-fr'] = "Abandonner :( Ne peut pas créer un instance XMLHTTP";
$text['message-give-up']['he-il'] = "לוותר:( לא יכול ליצור מקרה XMLHTTP";
$text['message-give-up']['it-it'] = "Abbandono :( Non riesco a creare un'instanza XMLHTTP";
$text['message-give-up']['nl-nl'] = "Opgegeven :( kan geen XMLHTTP verbinding maken";
$text['message-give-up']['pl-pl'] = "Śmiertelnia: (pol.). Cannot stworzył instancję XMLHTTP.";
$text['message-give-up']['pt-br'] = "Desistindo :( Não é possível criar uma instância XMLHTTP";
$text['message-give-up']['pt-pt'] = "Desistindo :( Não é possível criar uma instância XMLHTTP";
$text['message-give-up']['ro-ro'] = "Renunțare :( Nu se poate crea o instanță XMLHTTP";
$text['message-give-up']['ru-ru'] = "Операция отменена :( Невозможно создать XMLHTTP экземпляр";
$text['message-give-up']['sv-se'] = "Ger upp :( Kan inte skapa en XMLHTTP instans";
$text['message-give-up']['uk-ua'] = "Досягнення :( Не створювати екземпляр XMLHTTP";
$text['message-give-up']['zh-cn'] = "放弃 :( 无法创建 XMLHTTP 实例";
$text['message-give-up']['ja-jp'] = "諦めます:( XMLHTTP インスタンスを作成できません";
$text['message-give-up']['ko-kr'] = "포기합니다 :( XMLHTTP 인스턴스를 생성할 수 없습니다";

$text['message-problem']['en-us'] = "There was a problem with the request.";
$text['message-problem']['en-gb'] = "There was a problem with the request.";
$text['message-problem']['ar-eg'] = "كانت هناك مشكلة مع الطلب";
$text['message-problem']['de-at'] = "Es gab ein Problem mit der Anfrage.";
$text['message-problem']['de-ch'] = "Es gab ein Problem mit der Anfrage.";
$text['message-problem']['de-de'] = "Es gab ein Problem mit der Anfrage.";
$text['message-problem']['es-cl'] = "Hubo un problema con la petición.";
$text['message-problem']['es-mx'] = "Hubo un problema con la petición.";
$text['message-problem']['fr-ca'] = "Il y avait un problème avec la demande.";
$text['message-problem']['fr-fr'] = "Il y avait un problème avec la demande.";
$text['message-problem']['he-il'] = "הייתה בעיה עם הבקשה.";
$text['message-problem']['it-it'] = "C'è stato un problema con la richiesta.";
$text['message-problem']['nl-nl'] = "Er was een prbleem emt de aanvraag";
$text['message-problem']['pl-pl'] = "Na prośbę doszło do problemu.";
$text['message-problem']['pt-br'] = "Ocorreu um problema com o pedido.";
$text['message-problem']['pt-pt'] = "Ocorreu um problema com o pedido.";
$text['message-problem']['ro-ro'] = "A apărut o problemă cu cererea.";
$text['message-problem']['ru-ru'] = "Возникла проблема с запросом.";
$text['message-problem']['sv-se'] = "Det uppstod ett problem med begäran.";
$text['message-problem']['uk-ua'] = "Проблема з запитом.";
$text['message-problem']['zh-cn'] = "这个要求有个问题。";
$text['message-problem']['ja-jp'] = "リクエストに問題がありました。";
$text['message-problem']['ko-kr'] = "요청에 문제가 발생했습니다.";

?>
